source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

pod 'DKHelper', '~> 2.1.1'
pod 'MarqueeLabel', '~> 2.5.0'
pod 'LEColorPicker', '~> 1.0.3'
pod 'HockeySDK', '~> 3.8.5'
pod 'YWeatherAPI', '~> 1.0.6'
pod 'UIDevice-PasscodeStatus', '~> 0.0.2'
pod 'Reachability', '~> 3.2'
pod 'MagicalRecord', '~> 2.3.0'
pod 'MBProgressHUD', '~> 0.9.2'

inhibit_all_warnings!
